# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f5104bb683c8b1ba7b0e9fa4ee803f5"
name = "ellie-xyz-app"
application_url = "https://abc.apps.elliecee.xyz/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,write_draft_orders,read_cart_transforms,read_content,read_customers,read_discounts,read_discovery,read_files,read_inventory,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_orders,read_products,write_cart_transforms,write_content,write_customers,write_discounts,write_files,write_inventory,write_metaobject_definitions,write_metaobjects,write_online_store_pages,write_orders,write_products,write_app_proxy,read_app_proxy"


[auth]
redirect_urls = [ 
    "https://abc.apps.elliecee.xyz/shopify/auth/",
    "https://abc.apps.elliecee.xyz/shopify/login/",
    "https://abc.apps.elliecee.xyz/shopify/finalize/",
    "https://abc.apps.elliecee.xyz/shopify/logout/",
]


