# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7ed14495a96908782acad5452946a861"
name = "C+R For Seven Peaks"
handle = "c-r-for-seven-peaks"
application_url = "https://seven-peaks-85bd38c8443c.herokuapp.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,write_draft_orders,read_cart_transforms,read_content,read_customers,read_discounts,read_discovery,read_files,read_inventory,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_orders,read_products,write_cart_transforms,write_content,write_customers,write_discounts,write_files,write_inventory,write_metaobject_definitions,write_metaobjects,write_online_store_pages,write_orders,write_products"

[auth]
redirect_urls = [
  "https://seven-peaks-85bd38c8443c.herokuapp.com/shopify/auth/",
  "https://seven-peaks-85bd38c8443c.herokuapp.com/shopify/login/",
  "https://seven-peaks-85bd38c8443c.herokuapp.com/shopify/finalize/",
  "https://seven-peaks-85bd38c8443c.herokuapp.com/shopify/logout/"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
