# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "406fb0d6cce9b32bcc4686b042075f89"
name = "abc-xyz"
application_url = "https://abc.apps.elliecee.xyz"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_app_proxy,write_app_proxy,read_apps,read_cart_transforms,write_cart_transforms,read_all_cart_transforms,read_validations,write_validations,read_channels,write_channels,read_checkout_branding_settings,write_checkout_branding_settings,read_companies,write_companies,read_customers,write_customers,read_customer_data_erasure,write_customer_data_erasure,read_customer_merge,write_customer_merge,read_price_rules,write_price_rules,read_discounts,write_discounts,read_discounts_allocator_functions,write_discounts_allocator_functions,read_discovery,write_discovery,write_draft_orders,read_draft_orders,read_files,read_gift_cards,write_gift_cards,write_inventory,read_inventory,write_inventory_shipments,read_inventory_shipments,write_inventory_transfers,read_inventory_transfers,write_locations,read_locations,read_markets,write_markets,read_markets_home,write_markets_home,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_online_store_pages,write_online_store_pages,write_order_edits,read_order_edits,read_orders,write_orders,read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_products,write_products,read_publications,write_publications,read_returns,write_returns,read_script_tags,write_script_tags,read_content,write_content,write_own_subscription_contracts,read_own_subscription_contracts,write_theme_code,read_themes,write_themes,read_translations,write_translations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://abc.apps.elliecee.xyz",
  "https://abc.apps.elliecee.xyz/shopify/login",
  "https://abc.apps.elliecee.xyz/shopify/authorize",
  "https://abc.apps.elliecee.xyz/shopify/logout",
  "https://abc.apps.elliecee.xyz/shopify/finalize",
  "https://abc.apps.elliecee.xyz/shopify"
]

[app_proxy]
url = "/shopify-proxy"
subpath = "xyz"
prefix = "apps"
